#!/bin/bash

S_REPLICA=1
N_REPLICAS=1

for i in $(seq -f "%03g" $S_REPLICA $N_REPLICAS)
	do
	q_genrelax.py ./genrelax.proc \
	      --top ../../01_preparation3/01_preparation/RRDiol.top \
              --pdb ../../01_preparation3/01_preparation/RRDiol.pdb \
              --fep ../../01_preparation3/01_preparation/fep/RRD_Diol.fep \
              --rs ./run_relax_q.sh \
              --outdir relax_$i
	#cp input/sub_script.sh relax_$i
done
